#!/bin/bash
#
# scala with the examples,manualtests and threadcso library on the classpath
#
export JAVA_OPTS="-Xmx1024M -Xms128M --enable-preview -Dio.threadcso.debugger.port=9999"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home"
scala -cp /Users/sufrin/IdeaProjects/ThreadCSO/threadcso-examples-2.13+jdk21+2.0.0.jar:/Users/sufrin/IdeaProjects/ThreadCSO/threadcso-2.13+jdk21+2.0.0.jar "$@"
