#!/bin/bash
#
# scala with the examples,manualtests and threadcso library on the classpath
#
export JAVA_OPTS="-Xmx1024M -Xms128M --enable-preview -Dio.threadcso.debugger.port=9999"
export JAVA_HOME="/Users/sufrin/Downloads/jdk-20.jdk/Contents/Home"
scala -cp ./manualtests/target/scala-2.13/manualtests_2.13-1.3.jar:./examples/target/scala-2.13/examples_2.13-1.3.1.jar:threadcso-2.13+jdk20+1.3.jar "$@"
