#!/bin/bash
#  A script intended to support threadcso program development by hand, and/or
#  using IntelliJ and/or using sbt.
#
#  Usage:
#   cso   - discovers values for env variables JAVA_HOME, CSOPATH, JAVA_OPTS
#           by searching for '*.jar' files from the specified or default root, set
#           by the env variable $CSO_HOME, if it exists; else by the cso script.
#
#   The arguments may be prefixed with one of the following
#   modifies the paths used to search for '.jar' files.
#
#   -here         - the root is the current folder
#   -art          - search only for $CSO_HOME/*out/*.jar
#                 -        where IntelliJ artefacts are usually placed
#   -target args  - search only for $CSO_HOME/*target/*.jar
#                 -        where sbt usually places its packaged jars
#
#   cso  args          - run scala -cp $CSOPATH args in the discovered environment
#   csoc args          - as for cso, but run scalac (if csoc linked to cso)
#   cso  -cp PATH args - augment the discovered classpath by PATH, then as cso args
#  
#   cso  -sbt args     - run sbt args using JAVA_HOME and JAVA_OPTS
#   cso  -jars         - show details of the jars that will be on the CSOPATH
#   source cso         - exports the JAVA_HOME, CSOPATH, JAVA_OPTS variables
#
#  Installation: cso should be somewhere on PATH, with csoc linked to it symbolically
#  If there is a CSO_HOME environment variable set, then that is taken to be the
#  root folder from which library jars are discovered; otherwise the root defaults to:

CSO_HOME_DEFAULT=/Users/sufrin/IdeaProjects/ThreadCSO

#
# Default JAVA_HOME
#
JAVA_HOME=${JAVA_HOME-/Users/sufrin/Downloads/jdk-20.jdk/Contents/Home}


#
#
unset CSOPATH
unset JAVA_HOME
unset JAVA_OPTS
#
#
#
CSO_HOME=${CSO_HOME:-$CSO_HOME_DEFAULT}
JAVA_OPTS="-Xmx256M -Xms32M --enable-preview -Djavax.net.ssl.trustStore=$HOME/PRIVATE-cacerts"
#
#
#
###### -Djavax.net.debug=ssl:handshake

case $0 in
  *csoc)   PROGRAM=scalac;;
  *cso)    PROGRAM=scala;;
  *)       PROGRAM=echo;;
esac


#
# Interpret any special arguments
#
case $1 in

  -here)
     CSO_HOME=`pwd`
     shift
     ;;

  -sbt);;
  
  -h)
     cat <<EOT
Usage:
 cso   - discovers values for env variables JAVA_HOME, CSOPATH, JAVA_OPTS
         by searching for '*.jar' files from the specified or default root, set
         by the env variable \$CSO_HOME, if it exists; else by the cso script.

 The arguments may be prefixed with one of the following. Each
 affects the paths used to search for '.jar' files.

 -here         - the root is the current folder
 -art          - search only for \$CSO_HOME/*out/*.jar
                        where IntelliJ artefacts are usually placed
 -target args  - search only for \$CSO_HOME/*target/*.jar
                        where sbt usually places its packaged jars

 cso  args          - run scala -cp '\$CSOPATH' args in the discovered environment
 csoc args          - as for cso, but run scalac (if csoc linked to cso)
 cso  -cp PATH args - augment the discovered classpath by PATH, then as cso args

 cso  -sbt args     - run sbt args using JAVA_HOME and JAVA_OPTS
 cso  -jars         - show details of the jars that will be on the CSOPATH

Installation: cso should be somewhere on PATH, with csoc linked to it symbolically
If there is a CSO_HOME environment variable set, then that is taken to be the
root folder from which library jars are discovered; otherwise the root defaults to:
EOT
exit;;
esac

#
# Collect jar files for the path
#
if [ "$1" == "-art" ]
then
   shift
   JARS=$(find $CSO_HOME -path "*out/*.jar" )
elif [ "$1" == "-target" ]
then
   shift
   JARS=$(find $CSO_HOME -name "*.jar" -a -path "*target/*.jar" -a -not -path "*streams/*.jar")
else
   JARS=$(find $CSO_HOME -name "*.jar" -a -not \( -path "*sbt*" -o -path "*target*" \) )
fi

for jar in $JARS
do
  if [ "$CSOPATH" = "" ]
  then
    CSOPATH=$jar
  else
    CSOPATH=$jar:$CSOPATH
  fi
done


while [ "$1" = "-cp" -a "$#" -gt 1 ]
do
   CSOPATH=$CSOPATH:$2
   shift
   shift
done

export CSOPATH
export JAVA_HOME
export JAVA_OPTS


if [ "$1" = "-sbt" ]
then
   shift
   sbt "$@"
elif [ "$1" = "-jars" ]
then
   for jar in $JARS
   do
      [ -r $jar ] && ls -l $jar
   done
   exit
elif [ $# -ne 0 ]
then
   $PROGRAM -cp $CSOPATH "$@"
else
   printenv | egrep "(CSOPATH|JAVA_HOME|JAVA_OPTS)"
fi
