#!/bin/bash
#
#  Minimal build script for the "runner" scripts
#
source $(dirname $0)/configuration.sh
#
#
# Assign a literal string
ARGS='"$@"'
#
echo --- Making runner scripts
#
#
#
cat > runexample << ENDRUN
#!/bin/bash
#
# scala with the examples,manualtests and threadcso library on the classpath
#
export JAVA_OPTS="-Xmx1024M -Xms128M --enable-preview -Dio.threadcso.debugger.port=9999"
export JAVA_HOME="$JAVA_HOME"
scala -cp $RUNTESTS $ARGS
ENDRUN
chmod +x runexample
echo ./runexample ...
echo "   " runs "scala -cp $LIBJAR:$EXAMPLESJAR ..." 

cat > cso << ENDRUN
#!/bin/bash
#
# scala with threadcso library on the classpath
#
export JAVA_OPTS="-Xmx1024M -Xms128M --enable-preview"
export JAVA_HOME="$JAVA_HOME"
scala -cp $LIBJAR $ARGS
ENDRUN
chmod +x cso
echo ./cso ...
echo "   " runs "scala -cp $LIBJAR ..." 

cat > csoc << ENDRUN
#!/bin/bash
#
# scalac with threadcso library on the classpath
#
export JAVA_OPTS="-Xmx1024M -Xms128M --enable-preview"
export JAVA_HOME="$JAVA_HOME"
scalac -cp $LIBJAR $ARGS
ENDRUN
chmod +x csoc
echo ./csoc ...
echo "   " runs "scalac -cp $LIBJAR ..."

echo ---

